### ISSUE TITLE
pip install git+https://github.com/nve3pd/rhyme でインストールしたらエラーで死ぬ

### ISSUE THREAD

**Issue by ucpr** [nve3pd/rhyme#14]
```
pip install git+https://github.com/nve3pd/rhyme
```
でインストールしようとしたら
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/u_chi_ha_ra_/Work/rhyme/rhyme.py", line 12, in <module>
    conv = kakasi_py.getConverter()
  File "/home/u_chi_ha_ra_/.anyenv/envs/pyenv/versions/rhyme/lib/python3.6/site-packages/pykakasi/kakasi.py", line 115, in getConverter
    self._conv["J"] = J2a(method = self._option["r"])
  File "/home/u_chi_ha_ra_/.anyenv/envs/pyenv/versions/rhyme/lib/python3.6/site-packages/pykakasi/j2a.py", line 38, in __init__
    self._jconv = J2H()
  File "/home/u_chi_ha_ra_/.anyenv/envs/pyenv/versions/rhyme/lib/python3.6/site-packages/pykakasi/j2h.py", line 48, in __init__
    self._kanwa = kanwa()
  File "/home/u_chi_ha_ra_/.anyenv/envs/pyenv/versions/rhyme/lib/python3.6/site-packages/pykakasi/kanwa.py", line 31, in __init__
    self._kanwadict = dbm.open(dictpath,'r')
  File "/home/u_chi_ha_ra_/.anyenv/envs/pyenv/versions/3.6.3/lib/python3.6/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
```
で死ぬ問題

**Comment by ucpr** [comment]
AC
